# Generated by Django 3.1.7 on 2021-03-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteKeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
