# Generated by Django 3.1.7 on 2021-03-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteKeeper', '0002_auto_20210319_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='id',
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
